/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MusicBuzzImport } from './routes/musicBuzz'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MusicBuzzRoute = MusicBuzzImport.update({
  path: '/musicBuzz',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/musicBuzz': {
      id: '/musicBuzz'
      path: '/musicBuzz'
      fullPath: '/musicBuzz'
      preLoaderRoute: typeof MusicBuzzImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, MusicBuzzRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/musicBuzz"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/musicBuzz": {
      "filePath": "musicBuzz.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
